# Generated by Django 5.2.17 on 2026-09-04 20:31

import apps.accounts.models
import django.db.models.functions.text
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(blank=True, null=True, verbose_name="last login"),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True, verbose_name="ایمیل")),
                ("is_verified", models.BooleanField(default=False, verbose_name="ایمیل تأیید شده")),
                (
                    "phone",
                    models.CharField(
                        blank=True, default="", max_length=20, verbose_name="شماره تماس"
                    ),
                ),
                (
                    "telegram_id",
                    models.BigIntegerField(
                        blank=True, null=True, unique=True, verbose_name="شناسه تلگرام"
                    ),
                ),
                (
                    "telegram_username",
                    models.CharField(
                        blank=True, default="", max_length=64, verbose_name="نام کاربری تلگرام"
                    ),
                ),
                (
                    "telegram_linked_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="زمان اتصال تلگرام"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                ("is_staff", models.BooleanField(default=False, verbose_name="دسترسی پنل")),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="تاریخ عضویت"
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "کاربر",
                "verbose_name_plural": "کاربران",
                "constraints": [
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower("email"),
                        name="user_email_case_insensitive_unique",
                    )
                ],
            },
            managers=[
                ("objects", apps.accounts.models.UserManager()),
            ],
        ),
    ]
