# Generated by Django 5.2.17 on 2026-09-05 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="نام")),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True, max_length=100, unique=True, verbose_name="نامک"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, default="", max_length=300, verbose_name="توضیح کوتاه"
                    ),
                ),
                ("intro_html", models.TextField(blank=True, default="", verbose_name="متن معرفی")),
                (
                    "seo_title",
                    models.CharField(
                        blank=True, default="", max_length=70, verbose_name="عنوان سئو"
                    ),
                ),
                (
                    "seo_description",
                    models.CharField(
                        blank=True, default="", max_length=160, verbose_name="توضیح سئو"
                    ),
                ),
                ("sort_order", models.SmallIntegerField(default=0, verbose_name="ترتیب")),
            ],
            options={
                "verbose_name": "دسته\u200cبندی",
                "verbose_name_plural": "دسته\u200cبندی\u200cها",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="نام")),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True, max_length=150, unique=True, verbose_name="نامک"
                    ),
                ),
                (
                    "short_description",
                    models.CharField(
                        blank=True, default="", max_length=300, verbose_name="توضیح کوتاه"
                    ),
                ),
                (
                    "full_description",
                    models.TextField(blank=True, default="", verbose_name="توضیح کامل"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="products/", verbose_name="تصویر"
                    ),
                ),
                (
                    "delivery_type",
                    models.CharField(
                        choices=[
                            ("ready_account", "اکانت آماده"),
                            ("on_customer_account", "روی اکانت خود مشتری"),
                            ("code_license", "کد / لایسنس"),
                            ("gift_card", "گیفت کارت"),
                        ],
                        max_length=24,
                        verbose_name="نوع تحویل",
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        choices=[
                            ("global", "جهانی"),
                            ("ir", "ایران"),
                            ("us", "آمریکا"),
                            ("eu", "اروپا"),
                            ("tr", "ترکیه"),
                        ],
                        default="global",
                        max_length=24,
                        verbose_name="ریجن",
                    ),
                ),
                (
                    "warranty",
                    models.CharField(
                        choices=[
                            ("none", "بدون گارانتی"),
                            ("days_7", "۷ روز"),
                            ("full_period", "تا پایان دوره"),
                        ],
                        default="none",
                        max_length=24,
                        verbose_name="گارانتی",
                    ),
                ),
                (
                    "delivery_hours",
                    models.SmallIntegerField(default=24, verbose_name="مهلت تحویل (ساعت)"),
                ),
                (
                    "delivery_template",
                    models.TextField(blank=True, default="", verbose_name="قالب تحویل"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "پیش\u200cنویس"),
                            ("active", "فعال"),
                            ("unavailable", "ناموجود"),
                        ],
                        default="draft",
                        max_length=16,
                        verbose_name="وضعیت",
                    ),
                ),
                ("search_text", models.TextField(blank=True, default="", editable=False)),
                (
                    "seo_title",
                    models.CharField(
                        blank=True, default="", max_length=70, verbose_name="عنوان سئو"
                    ),
                ),
                (
                    "seo_description",
                    models.CharField(
                        blank=True, default="", max_length=160, verbose_name="توضیح سئو"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="catalog.category",
                        verbose_name="دسته\u200cبندی",
                    ),
                ),
            ],
            options={
                "verbose_name": "محصول",
                "verbose_name_plural": "محصولات",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ProductSpec",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="عنوان")),
                ("value", models.CharField(max_length=255, verbose_name="مقدار")),
                ("sort_order", models.SmallIntegerField(default=0, verbose_name="ترتیب")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="specs",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "مشخصه",
                "verbose_name_plural": "مشخصات",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="عنوان")),
                (
                    "duration_days",
                    models.IntegerField(blank=True, null=True, verbose_name="مدت (روز)"),
                ),
                (
                    "cost_price",
                    models.DecimalField(decimal_places=0, max_digits=12, verbose_name="قیمت خرید"),
                ),
                (
                    "sale_price",
                    models.DecimalField(decimal_places=0, max_digits=12, verbose_name="قیمت فروش"),
                ),
                (
                    "promo_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        max_digits=12,
                        null=True,
                        verbose_name="قیمت تخفیفی",
                    ),
                ),
                (
                    "promo_starts_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="شروع تخفیف"),
                ),
                (
                    "promo_ends_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="پایان تخفیف"),
                ),
                ("is_available", models.BooleanField(default=True, verbose_name="موجود")),
                (
                    "requires_customer_input",
                    models.BooleanField(default=False, verbose_name="نیاز به اطلاعات مشتری"),
                ),
                (
                    "customer_input_label",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="برچسب اطلاعات مشتری"
                    ),
                ),
                (
                    "supplier_url",
                    models.URLField(blank=True, default="", verbose_name="لینک تأمین\u200cکننده"),
                ),
                ("sort_order", models.SmallIntegerField(default=0, verbose_name="ترتیب")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plans",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "پلن",
                "verbose_name_plural": "پلن\u200cها",
                "ordering": ["sort_order", "id"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("promo_price__isnull", True),
                            models.Q(
                                ("promo_price__gt", 0), ("promo_price__lt", models.F("sale_price"))
                            ),
                            _connector="OR",
                        ),
                        name="plan_promo_price_below_sale_price",
                        violation_error_message="قیمت تخفیفی باید بیشتر از صفر و کمتر از قیمت فروش باشد.",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("promo_starts_at__isnull", True),
                            ("promo_ends_at__isnull", True),
                            ("promo_starts_at__lt", models.F("promo_ends_at")),
                            _connector="OR",
                        ),
                        name="plan_promo_window_starts_before_it_ends",
                        violation_error_message="شروع تخفیف باید قبل از پایان آن باشد.",
                    ),
                ],
            },
        ),
    ]
