# Generated by Django 5.2.17 on 2026-09-21 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="plan",
            constraint=models.CheckConstraint(
                condition=models.Q(("cost_price__gte", 0), ("sale_price__gte", 0)),
                name="plan_prices_not_negative",
                violation_error_message="قیمت خرید و قیمت فروش نمی\u200cتوانند منفی باشند.",
            ),
        ),
        migrations.AddConstraint(
            model_name="plan",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("duration_days__isnull", True), ("duration_days__gt", 0), _connector="OR"
                ),
                name="plan_duration_positive_or_unlimited",
                violation_error_message="مدت پلن باید دست\u200cکم یک روز باشد، یا خالی برای بی\u200cپایان.",
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.CheckConstraint(
                condition=models.Q(("delivery_hours__gte", 1), ("delivery_hours__lte", 48)),
                name="product_delivery_hours_1_to_48",
                violation_error_message="مهلت تحویل باید بین ۱ تا ۴۸ ساعت باشد.",
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["draft", "active", "unavailable"])),
                name="product_status_valid",
                violation_error_message="وضعیت محصول معتبر نیست.",
            ),
        ),
    ]
